szkolny-eu/szkolny-android

README.md

Correction of spelling and punctuation errors and improved text appearance.

Correction of spelling and punctuation errors

---

.github/utils/.gitignore
.github/utils/_get_password.py
.github/utils/_utils.py
.github/utils/bump_nightly.py
.github/utils/bump_version.py
.github/utils/extract_changelogs.py
.github/utils/rename_artifacts.py
.github/utils/save_version.py
.github/utils/sign.py
.github/utils/webhook_discord.py
.github/workflows/build-nightly-apk.yml
.github/workflows/build-release-aab-play.yml
.github/workflows/build-release-apk.yml

This PR adds GitHub Actions workflows for deploying release builds, nightly builds and Google Play release build.

Add GitHub Actions

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

Update copyright date

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/task/PostNotifications.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Notification.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/notifications/NotificationsAdapter.kt
app/src/main/res/layout/notifications_list_item.xml

Add notification icons

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/task/Notifications.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/task/PostNotifications.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/AppDb.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Notification.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/migration/Migration93.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/widgets/notifications/WidgetNotificationsFactory.kt
app/src/main/res/values/strings.xml

[Notifications] Add long description text

---

app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/timetable/GenerateBlockTimetableDialog.kt

[UI] Fix block timetable export.

---

app/src/main/res/layout/attendance_list_fragment.xml
app/src/main/res/layout/attendance_summary_fragment.xml
app/src/main/res/layout/card_home_grades.xml
app/src/main/res/layout/card_home_template.xml
app/src/main/res/layout/grades_item_stats.xml
app/src/main/res/layout/grades_list_fragment.xml
app/src/main/res/layout/homework_list_fragment.xml
app/src/main/res/layout/messages_list_fragment.xml
app/src/main/res/layout/notifications_list_fragment.xml
app/src/main/res/layout/template_list_fragment.xml
app/src/main/res/layout/template_list_page_fragment.xml

This fixes a horrible misalignment I once saw and now cannot unsee.

[UI] Center "no data" text view.

---

app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/agenda/AgendaFragment.kt

This creates event types when missing upon opening agenda.

[DB] Workaround missing event types after profile archiving.

---

app/build.gradle

[UI] Fix multiplicated day dialog in Agenda.

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/Regexes.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/DataEdudziennik.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebExams.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebGrades.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebHomework.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebStart.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebTimetable.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/MobidziennikFeatures.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/MobidziennikData.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebTimetable.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/DataPodlasie.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiFinalGrades.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiGrades.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiMain.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiTimetable.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/models/Data.kt

This allows to download future timetable in Mobidziennik (over 2 weeks forward).

[API/Mobidziennik] Add Web timetable scrapper.

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/hebe/VulcanHebeAttendance.kt

This fixes a changed `Id` key in attendance JSON response.

[API/Vulcan] Fix missing attendance.

---

app/src/main/java/pl/szczodrzynski/edziennik/App.kt
app/src/main/java/pl/szczodrzynski/edziennik/MainActivity.kt
app/src/main/java/pl/szczodrzynski/edziennik/config/Config.kt
app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ConfigExtensions.kt
app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ConfigMigration.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/EdziennikTask.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/events/RegisterAvailabilityEvent.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Profile.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/firebase/SzkolnyAppFirebase.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/RegisterUnavailableDialog.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabFragment.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabPageFragment.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/home/HomeFragment.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/home/cards/HomeAvailabilityCard.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/login/LoginChooserFragment.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/login/LoginPrizeFragment.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/managers/AvailabilityManager.kt
app/src/main/res/layout/lab_fragment.xml

This PR refactors the code related to register availability checking. It also adds new options to the Lab, such as availability checking toggle (useful when running unofficial builds), resetting API signature (for reinstalling unofficial version to official) and rebuilding App.config (when editing App.config using JSON tab).

[API] Refactor register availability checking module.

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/Regexes.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/Mobidziennik.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebCalendar.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebGetEvent.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/models/Data.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/task/Notifications.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/AppDb.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/dao/MetadataDao.java
app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Event.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/full/EventFull.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/migration/Migration94.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/firebase/SzkolnyAppFirebase.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/event/EventDetailsDialog.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabPageFragment.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/widgets/timetable/WidgetTimetableProvider.kt

Closes #20.
The code downloads full event description when needed. This allows to save the correct event topic, body, added date and adding teacher's ID.

[API/Mobidziennik] Implement getting full event description.

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/api/MobidziennikApiTeams.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/api/MobidziennikApiTimetable.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebTimetable.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/models/DataRemoveModel.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/AppDb.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/dao/TimetableDao.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Lesson.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/db/migration/Migration95.kt

This PR fixes not-removing extra lessons and the HTML scrapping algorithm of the timetable.
The extra lessons are now visible for current week and past/future weeks, and synced every 2 days.

[API/Mobidziennik] Implement syncing extra lessons.

---

app/src/main/java/pl/szczodrzynski/edziennik/Extensions.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeChipCreator.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeChipTokenizer.kt
app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeFragment.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/TextInputKeyboardEdit.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/html/BetterHtml.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/span/BoldSpan.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/span/ImprovedBulletSpan.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/span/ItalicSpan.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/span/SubscriptSizeSpan.kt
app/src/main/java/pl/szczodrzynski/edziennik/utils/span/SuperscriptSizeSpan.kt
app/src/main/res/layout/messages_compose_fragment.xml
app/src/main/res/values/strings.xml

This PR adds support for styling text when composing messages.

[Messages/Compose] Add text styling support.

---

app/proguard-rules.pro
app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ProfileConfigMigration.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/VulcanHebe.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/hebe/VulcanHebeMain.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/models/Data.kt

- missing Proguard rule for Note entity
- notes card was the only card on newly added profiles
- TeamClass could be missing in Vulcan

Fix minor problems with Notes

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/data/api/LibrusApiNotices.kt

[API/Librus] Fix getting teacher name in notices.

---

app/src/main/res/values-en/strings.xml

[Strings] Translate home timetable card "all lessons" to English.

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/data/messages/LibrusMessagesGetMessage.kt

[API/Librus] Fix getting read date in messages for multiple receivers.

---

app/src/main/java/pl/szczodrzynski/edziennik/data/api/Constants.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/Regexes.kt
app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/login/LibrusLoginPortal.kt

[API/Librus] Fix login.
